### ISSUE TITLE
Search index is out of sync with the database causing non-existent articles to show up in search

### ISSUE THREAD

**Issue by KentShikama** [thestudentlife/Manhattan-Project#101]
See https://github.com/thestudentlife/thestudentlife/issues/87

![screen shot 2016-11-06 at 9 02 08 pm](https://cloud.githubusercontent.com/assets/6329898/20046950/53dccda2-a464-11e6-9e71-a6adce810e78.png)

**Comment by ZiqiXiong** [comment]
@KentShikama
