### ISSUE TITLE
Test ticket from Code Climate

### ISSUE THREAD

**Issue by KentShikama** [thestudentlife/Manhattan-Project#50]

**Comment by ZiqiXiong** [comment]
Lol what is code climate?

On Mon, Jul 27, 2015 at 11:24 PM, Kent Shikama notifications@github.com
wrote:

> Closed #50 https://github.com/thestudentlife/Manhattan-Project/issues/50
> .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/thestudentlife/Manhattan-Project/issues/50#event-366864939
> .

## 

## 

Ziqi (ZQ) Xiong 熊子淇
_Pomona College '17_
ziqi.xiong@pomona.edu, 909-450-1216
170 E. Sixth Street – Mailbox #1739, Claremont, CA 91711-7004
