### ISSUE TITLE
Photo caption formatting

### ISSUE THREAD

**Issue by ktidmarsh** [thestudentlife/Manhattan-Project#84]
It'd be really cool to have the photo captions in a smaller font associated with the image rather than having to type it into the article's text box. Most other websites have it this way. See this random Buzzfeed story to see what I mean: http://www.buzzfeed.com/aramroston/the-pentagons-shopping-list-of-weapons-to-fight-isis#.gmOV6L0yyE

**Comment by ZiqiXiong** [comment]
Hi Kevin, you don't need to type the photo caption into the article text box. You can change it by editing the "alternative text" field of images through the text editor(double click on the image). Please forward this to the other editors.

**Comment by KentShikama** [comment]
@ZiqiXiong Maybe he is just talking about the formatting of the alt text? In other words, how it displays on the website.

**Comment by ZiqiXiong** [comment]
@theworldbright My comment is in reply to "rather than having to type it into the article's text box".
