### ISSUE TITLE
Some graduated students' bylines are no longer showing up

### ISSUE THREAD

**Issue by ktidmarsh** [thestudentlife/Manhattan-Project#92]
E.g.: http://tsl.news/news/5274/

**Comment by ZiqiXiong** [comment]
@ktidmarsh  I suspect that this happens when their accounts are deleted. Can you let the editors know that they should downgrade rather than delete accounts when their owners graduate?

**Comment by ktidmarsh** [comment]
Got it. I know what articles I wrote, so can you give the workflow account
I just made (kevintidmarsh) editor permissions so I can fix the problem
manually?

**Comment by ZiqiXiong** [comment]
@ktidmarsh Done!
